/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HowImport } from './routes/how'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileUseridImport } from './routes/profile/$userid'
import { Route as IcpCreateImport } from './routes/icp/create'
import { Route as IcpWalletPidImport } from './routes/icp/wallet/$pid'
import { Route as IcpTokenIdImport } from './routes/icp/token/$id'

// Create/Update Routes

const HowRoute = HowImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUseridRoute = ProfileUseridImport.update({
  id: '/profile/$userid',
  path: '/profile/$userid',
  getParentRoute: () => rootRoute,
} as any)

const IcpCreateRoute = IcpCreateImport.update({
  id: '/icp/create',
  path: '/icp/create',
  getParentRoute: () => rootRoute,
} as any)

const IcpWalletPidRoute = IcpWalletPidImport.update({
  id: '/icp/wallet/$pid',
  path: '/icp/wallet/$pid',
  getParentRoute: () => rootRoute,
} as any)

const IcpTokenIdRoute = IcpTokenIdImport.update({
  id: '/icp/token/$id',
  path: '/icp/token/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowImport
      parentRoute: typeof rootRoute
    }
    '/icp/create': {
      id: '/icp/create'
      path: '/icp/create'
      fullPath: '/icp/create'
      preLoaderRoute: typeof IcpCreateImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userid': {
      id: '/profile/$userid'
      path: '/profile/$userid'
      fullPath: '/profile/$userid'
      preLoaderRoute: typeof ProfileUseridImport
      parentRoute: typeof rootRoute
    }
    '/icp/token/$id': {
      id: '/icp/token/$id'
      path: '/icp/token/$id'
      fullPath: '/icp/token/$id'
      preLoaderRoute: typeof IcpTokenIdImport
      parentRoute: typeof rootRoute
    }
    '/icp/wallet/$pid': {
      id: '/icp/wallet/$pid'
      path: '/icp/wallet/$pid'
      fullPath: '/icp/wallet/$pid'
      preLoaderRoute: typeof IcpWalletPidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/icp/create': typeof IcpCreateRoute
  '/profile/$userid': typeof ProfileUseridRoute
  '/icp/token/$id': typeof IcpTokenIdRoute
  '/icp/wallet/$pid': typeof IcpWalletPidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/icp/create': typeof IcpCreateRoute
  '/profile/$userid': typeof ProfileUseridRoute
  '/icp/token/$id': typeof IcpTokenIdRoute
  '/icp/wallet/$pid': typeof IcpWalletPidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/icp/create': typeof IcpCreateRoute
  '/profile/$userid': typeof ProfileUseridRoute
  '/icp/token/$id': typeof IcpTokenIdRoute
  '/icp/wallet/$pid': typeof IcpWalletPidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how'
    | '/icp/create'
    | '/profile/$userid'
    | '/icp/token/$id'
    | '/icp/wallet/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/icp/create'
    | '/profile/$userid'
    | '/icp/token/$id'
    | '/icp/wallet/$pid'
  id:
    | '__root__'
    | '/'
    | '/how'
    | '/icp/create'
    | '/profile/$userid'
    | '/icp/token/$id'
    | '/icp/wallet/$pid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  IcpCreateRoute: typeof IcpCreateRoute
  ProfileUseridRoute: typeof ProfileUseridRoute
  IcpTokenIdRoute: typeof IcpTokenIdRoute
  IcpWalletPidRoute: typeof IcpWalletPidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  IcpCreateRoute: IcpCreateRoute,
  ProfileUseridRoute: ProfileUseridRoute,
  IcpTokenIdRoute: IcpTokenIdRoute,
  IcpWalletPidRoute: IcpWalletPidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/how",
        "/icp/create",
        "/profile/$userid",
        "/icp/token/$id",
        "/icp/wallet/$pid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/how": {
      "filePath": "how.tsx"
    },
    "/icp/create": {
      "filePath": "icp/create.tsx"
    },
    "/profile/$userid": {
      "filePath": "profile/$userid.tsx"
    },
    "/icp/token/$id": {
      "filePath": "icp/token/$id.tsx"
    },
    "/icp/wallet/$pid": {
      "filePath": "icp/wallet/$pid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
