/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HowImport } from './routes/how'
import { Route as IndexImport } from './routes/index'
import { Route as IcpCreateImport } from './routes/icp/create'
import { Route as BitcoinCreateImport } from './routes/bitcoin/create'
import { Route as MobileIcpDepositWithdrawImport } from './routes/mobile/icp/deposit-withdraw'
import { Route as IcpWalletPidImport } from './routes/icp/wallet/$pid'
import { Route as IcpTokenIdImport } from './routes/icp/token/$id'
import { Route as IcpProfileUseridImport } from './routes/icp/profile/$userid'
import { Route as BitcoinWalletPidImport } from './routes/bitcoin/wallet/$pid'
import { Route as BitcoinTokenIdImport } from './routes/bitcoin/token/$id'
import { Route as BitcoinProfileUseridImport } from './routes/bitcoin/profile/$userid'

// Create/Update Routes

const HowRoute = HowImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IcpCreateRoute = IcpCreateImport.update({
  id: '/icp/create',
  path: '/icp/create',
  getParentRoute: () => rootRoute,
} as any)

const BitcoinCreateRoute = BitcoinCreateImport.update({
  id: '/bitcoin/create',
  path: '/bitcoin/create',
  getParentRoute: () => rootRoute,
} as any)

const MobileIcpDepositWithdrawRoute = MobileIcpDepositWithdrawImport.update({
  id: '/mobile/icp/deposit-withdraw',
  path: '/mobile/icp/deposit-withdraw',
  getParentRoute: () => rootRoute,
} as any)

const IcpWalletPidRoute = IcpWalletPidImport.update({
  id: '/icp/wallet/$pid',
  path: '/icp/wallet/$pid',
  getParentRoute: () => rootRoute,
} as any)

const IcpTokenIdRoute = IcpTokenIdImport.update({
  id: '/icp/token/$id',
  path: '/icp/token/$id',
  getParentRoute: () => rootRoute,
} as any)

const IcpProfileUseridRoute = IcpProfileUseridImport.update({
  id: '/icp/profile/$userid',
  path: '/icp/profile/$userid',
  getParentRoute: () => rootRoute,
} as any)

const BitcoinWalletPidRoute = BitcoinWalletPidImport.update({
  id: '/bitcoin/wallet/$pid',
  path: '/bitcoin/wallet/$pid',
  getParentRoute: () => rootRoute,
} as any)

const BitcoinTokenIdRoute = BitcoinTokenIdImport.update({
  id: '/bitcoin/token/$id',
  path: '/bitcoin/token/$id',
  getParentRoute: () => rootRoute,
} as any)

const BitcoinProfileUseridRoute = BitcoinProfileUseridImport.update({
  id: '/bitcoin/profile/$userid',
  path: '/bitcoin/profile/$userid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowImport
      parentRoute: typeof rootRoute
    }
    '/bitcoin/create': {
      id: '/bitcoin/create'
      path: '/bitcoin/create'
      fullPath: '/bitcoin/create'
      preLoaderRoute: typeof BitcoinCreateImport
      parentRoute: typeof rootRoute
    }
    '/icp/create': {
      id: '/icp/create'
      path: '/icp/create'
      fullPath: '/icp/create'
      preLoaderRoute: typeof IcpCreateImport
      parentRoute: typeof rootRoute
    }
    '/bitcoin/profile/$userid': {
      id: '/bitcoin/profile/$userid'
      path: '/bitcoin/profile/$userid'
      fullPath: '/bitcoin/profile/$userid'
      preLoaderRoute: typeof BitcoinProfileUseridImport
      parentRoute: typeof rootRoute
    }
    '/bitcoin/token/$id': {
      id: '/bitcoin/token/$id'
      path: '/bitcoin/token/$id'
      fullPath: '/bitcoin/token/$id'
      preLoaderRoute: typeof BitcoinTokenIdImport
      parentRoute: typeof rootRoute
    }
    '/bitcoin/wallet/$pid': {
      id: '/bitcoin/wallet/$pid'
      path: '/bitcoin/wallet/$pid'
      fullPath: '/bitcoin/wallet/$pid'
      preLoaderRoute: typeof BitcoinWalletPidImport
      parentRoute: typeof rootRoute
    }
    '/icp/profile/$userid': {
      id: '/icp/profile/$userid'
      path: '/icp/profile/$userid'
      fullPath: '/icp/profile/$userid'
      preLoaderRoute: typeof IcpProfileUseridImport
      parentRoute: typeof rootRoute
    }
    '/icp/token/$id': {
      id: '/icp/token/$id'
      path: '/icp/token/$id'
      fullPath: '/icp/token/$id'
      preLoaderRoute: typeof IcpTokenIdImport
      parentRoute: typeof rootRoute
    }
    '/icp/wallet/$pid': {
      id: '/icp/wallet/$pid'
      path: '/icp/wallet/$pid'
      fullPath: '/icp/wallet/$pid'
      preLoaderRoute: typeof IcpWalletPidImport
      parentRoute: typeof rootRoute
    }
    '/mobile/icp/deposit-withdraw': {
      id: '/mobile/icp/deposit-withdraw'
      path: '/mobile/icp/deposit-withdraw'
      fullPath: '/mobile/icp/deposit-withdraw'
      preLoaderRoute: typeof MobileIcpDepositWithdrawImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/bitcoin/create': typeof BitcoinCreateRoute
  '/icp/create': typeof IcpCreateRoute
  '/bitcoin/profile/$userid': typeof BitcoinProfileUseridRoute
  '/bitcoin/token/$id': typeof BitcoinTokenIdRoute
  '/bitcoin/wallet/$pid': typeof BitcoinWalletPidRoute
  '/icp/profile/$userid': typeof IcpProfileUseridRoute
  '/icp/token/$id': typeof IcpTokenIdRoute
  '/icp/wallet/$pid': typeof IcpWalletPidRoute
  '/mobile/icp/deposit-withdraw': typeof MobileIcpDepositWithdrawRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/bitcoin/create': typeof BitcoinCreateRoute
  '/icp/create': typeof IcpCreateRoute
  '/bitcoin/profile/$userid': typeof BitcoinProfileUseridRoute
  '/bitcoin/token/$id': typeof BitcoinTokenIdRoute
  '/bitcoin/wallet/$pid': typeof BitcoinWalletPidRoute
  '/icp/profile/$userid': typeof IcpProfileUseridRoute
  '/icp/token/$id': typeof IcpTokenIdRoute
  '/icp/wallet/$pid': typeof IcpWalletPidRoute
  '/mobile/icp/deposit-withdraw': typeof MobileIcpDepositWithdrawRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/bitcoin/create': typeof BitcoinCreateRoute
  '/icp/create': typeof IcpCreateRoute
  '/bitcoin/profile/$userid': typeof BitcoinProfileUseridRoute
  '/bitcoin/token/$id': typeof BitcoinTokenIdRoute
  '/bitcoin/wallet/$pid': typeof BitcoinWalletPidRoute
  '/icp/profile/$userid': typeof IcpProfileUseridRoute
  '/icp/token/$id': typeof IcpTokenIdRoute
  '/icp/wallet/$pid': typeof IcpWalletPidRoute
  '/mobile/icp/deposit-withdraw': typeof MobileIcpDepositWithdrawRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how'
    | '/bitcoin/create'
    | '/icp/create'
    | '/bitcoin/profile/$userid'
    | '/bitcoin/token/$id'
    | '/bitcoin/wallet/$pid'
    | '/icp/profile/$userid'
    | '/icp/token/$id'
    | '/icp/wallet/$pid'
    | '/mobile/icp/deposit-withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/bitcoin/create'
    | '/icp/create'
    | '/bitcoin/profile/$userid'
    | '/bitcoin/token/$id'
    | '/bitcoin/wallet/$pid'
    | '/icp/profile/$userid'
    | '/icp/token/$id'
    | '/icp/wallet/$pid'
    | '/mobile/icp/deposit-withdraw'
  id:
    | '__root__'
    | '/'
    | '/how'
    | '/bitcoin/create'
    | '/icp/create'
    | '/bitcoin/profile/$userid'
    | '/bitcoin/token/$id'
    | '/bitcoin/wallet/$pid'
    | '/icp/profile/$userid'
    | '/icp/token/$id'
    | '/icp/wallet/$pid'
    | '/mobile/icp/deposit-withdraw'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  BitcoinCreateRoute: typeof BitcoinCreateRoute
  IcpCreateRoute: typeof IcpCreateRoute
  BitcoinProfileUseridRoute: typeof BitcoinProfileUseridRoute
  BitcoinTokenIdRoute: typeof BitcoinTokenIdRoute
  BitcoinWalletPidRoute: typeof BitcoinWalletPidRoute
  IcpProfileUseridRoute: typeof IcpProfileUseridRoute
  IcpTokenIdRoute: typeof IcpTokenIdRoute
  IcpWalletPidRoute: typeof IcpWalletPidRoute
  MobileIcpDepositWithdrawRoute: typeof MobileIcpDepositWithdrawRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  BitcoinCreateRoute: BitcoinCreateRoute,
  IcpCreateRoute: IcpCreateRoute,
  BitcoinProfileUseridRoute: BitcoinProfileUseridRoute,
  BitcoinTokenIdRoute: BitcoinTokenIdRoute,
  BitcoinWalletPidRoute: BitcoinWalletPidRoute,
  IcpProfileUseridRoute: IcpProfileUseridRoute,
  IcpTokenIdRoute: IcpTokenIdRoute,
  IcpWalletPidRoute: IcpWalletPidRoute,
  MobileIcpDepositWithdrawRoute: MobileIcpDepositWithdrawRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/how",
        "/bitcoin/create",
        "/icp/create",
        "/bitcoin/profile/$userid",
        "/bitcoin/token/$id",
        "/bitcoin/wallet/$pid",
        "/icp/profile/$userid",
        "/icp/token/$id",
        "/icp/wallet/$pid",
        "/mobile/icp/deposit-withdraw"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/how": {
      "filePath": "how.tsx"
    },
    "/bitcoin/create": {
      "filePath": "bitcoin/create.tsx"
    },
    "/icp/create": {
      "filePath": "icp/create.tsx"
    },
    "/bitcoin/profile/$userid": {
      "filePath": "bitcoin/profile/$userid.tsx"
    },
    "/bitcoin/token/$id": {
      "filePath": "bitcoin/token/$id.tsx"
    },
    "/bitcoin/wallet/$pid": {
      "filePath": "bitcoin/wallet/$pid.tsx"
    },
    "/icp/profile/$userid": {
      "filePath": "icp/profile/$userid.tsx"
    },
    "/icp/token/$id": {
      "filePath": "icp/token/$id.tsx"
    },
    "/icp/wallet/$pid": {
      "filePath": "icp/wallet/$pid.tsx"
    },
    "/mobile/icp/deposit-withdraw": {
      "filePath": "mobile/icp/deposit-withdraw.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
